version: '3.5'
services:
  api:
    build:      
      context: ./
      dockerfile: Dockerfile
    command: dev
    ports:
      - '3000:3000'
    # depends_on:
    #   - mongo
    volumes:
      - .:/app:delegated
      - ./package.json:/app/package.json:delegated      
    environment:
      # - MONGO_URL=mongodb://mongo:27017/noudada
      - API_URL=noudada.ngrok.io
      - MONGO_URL=mongodb+srv://admin_noudada:6_QmtB3UYCXfLkr@noudada.cwkxv.mongodb.net/noudada_Admin?retryWrites=true&w=majority
      - JWT_SECRET=v9y$B&E)H@McQfTjWmZq4t7w!z%C*F-J
      - JWT_LIFETIME=30d
      - TWILIO_ACCOUNT_SID=AC168f4128a705d3f0f8a192bbcdee03aa
      - TWILIO_AUTH_TOKEN=2c5844ad81c567a6cb026292bcfd443a
      - TWILIO_PHONE_NUMBER=+19707158771
      - APP_URL=http://127.0.0.1:4200
      - SENDGRID_API_KEY=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
      - SGSENDER=dev@noudada.com
      - OTPTEMPLATEID=d-1785b3f16f1e4ea8af9306436218bd8a
      - SUPER_ADMIN_EMAIL=amanrawatamg@gmail.com
      - PUBLISHABLE_KEY=pk_test_51L88PoHuM2wzausDq5lbGMU4MeL5losu8iLNBUYAXaAJyFOkxKuBNXaLOEw8BY3HWDZpErFpjo8ErkF3XwxK4DVr005t4vn4bJ
      - SECRET_KEY=sk_test_51L88PoHuM2wzausDnMPC4b1AzllPmOav3yW5DsF7ddtNFZTKSWAAOp6PcjCutQlig2p1drlog7vfJVBUDiaD54RJ00YHuiwSAC
    networks:
      - noudata_net

  # mongo:
  #   image: mongo:latest
  #   networks:
  #     - noudata_net
  #   logging:
  #     options:
  #       max-size: 10m
  #   ports:
  #     - '27017:27017'

networks:
  noudata_net:
    driver: bridge